### ISSUE TITLE
Update React version

### ISSUE THREAD

**Issue by KarlBaumann** [FilipChalupa/react-use-pwa-install#1]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/11026930/114425256-2f509f80-9bb9-11eb-8c1c-126aa5ca2550.png">

**Comment by FilipChalupa** [comment]
I've just initialized a Gatbsy starter and can't reproduce your issue. Can you tell me the last command you've run? 

This works for me: https://github.com/FilipChalupa/react-use-pwa-install-peer-test/commit/305031d7c38946720bcdd726f0b19c3784446d77

![image](https://user-images.githubusercontent.com/1045362/114427050-fca7a680-9bba-11eb-893a-53e47d0184bb.png)

Maybe i'm using peer dependecies wrong.

**Comment by KarlBaumann** [comment]
I am using later React version. It is basically complaining that my version is newer.
I have 17.0.2 but it asks for 17.0.1 if I understand correctly.

**Comment by FilipChalupa** [comment]
I had older `npm`. After upgrading it and React I get same error as you.

**Comment by FilipChalupa** [comment]
I've updated the package to `react-use-pwa-install@0.1.1`. I should work with the latest `npm` now.

**Comment by KarlBaumann** [comment]
thanks! working good now!
